# prettier-ignore
apiVersion: 3
name: royco-goldsky-pipeline
status: ACTIVE
sources:
  recipe_raw_market_reference:
    name: raw_market
    subgraphs:
      - name: royco-recipe-sepolia
        version: {{recipe_version}}
      - name: royco-recipe-mainnet
        version: {{recipe_version}}
      - name: royco-recipe-arbitrum-sepolia
        version: {{recipe_version}}
      - name: royco-recipe-arbitrum-one
        version: {{recipe_version}}
      - name: royco-recipe-base-sepolia
        version: {{recipe_version}}
      - name: royco-recipe-base
        version: {{recipe_version}}
    type: subgraph_entity
  recipe_raw_offer_reference:
    name: raw_offer
    subgraphs:
      - name: royco-recipe-sepolia
        version: {{recipe_version}}
      - name: royco-recipe-mainnet
        version: {{recipe_version}}
      - name: royco-recipe-arbitrum-sepolia
        version: {{recipe_version}}
      - name: royco-recipe-arbitrum-one
        version: {{recipe_version}}
      - name: royco-recipe-base-sepolia
        version: {{recipe_version}}
      - name: royco-recipe-base
        version: {{recipe_version}}
    type: subgraph_entity
  recipe_raw_activity_reference:
    name: raw_activity
    subgraphs:
      - name: royco-recipe-sepolia
        version: {{recipe_version}}
      - name: royco-recipe-mainnet
        version: {{recipe_version}}
      - name: royco-recipe-arbitrum-sepolia
        version: {{recipe_version}}
      - name: royco-recipe-arbitrum-one
        version: {{recipe_version}}
      - name: royco-recipe-base-sepolia
        version: {{recipe_version}}
      - name: royco-recipe-base
        version: {{recipe_version}}
    type: subgraph_entity
  recipe_raw_account_balance_reference:
    name: raw_account_balance
    subgraphs:
      - name: royco-recipe-sepolia
        version: {{recipe_version}}
      - name: royco-recipe-mainnet
        version: {{recipe_version}}
      - name: royco-recipe-arbitrum-sepolia
        version: {{recipe_version}}
      - name: royco-recipe-arbitrum-one
        version: {{recipe_version}}
      - name: royco-recipe-base-sepolia
        version: {{recipe_version}}
      - name: royco-recipe-base
        version: {{recipe_version}}
    type: subgraph_entity 
  recipe_raw_position_reference:
    name: raw_position
    subgraphs:
      - name: royco-recipe-sepolia
        version: {{recipe_version}}
      - name: royco-recipe-mainnet
        version: {{recipe_version}}
      - name: royco-recipe-arbitrum-sepolia
        version: {{recipe_version}}
      - name: royco-recipe-arbitrum-one
        version: {{recipe_version}}
      - name: royco-recipe-base-sepolia
        version: {{recipe_version}}
      - name: royco-recipe-base
        version: {{recipe_version}}
    type: subgraph_entity
  vault_raw_market_reference:
    name: raw_market
    subgraphs:
      - name: royco-vault-sepolia
        version: {{vault_version}}
      - name: royco-vault-mainnet
        version: {{vault_version}}
      - name: royco-vault-arbitrum-sepolia
        version: {{vault_version}}
      - name: royco-vault-arbitrum-one
        version: {{vault_version}}
      - name: royco-vault-base-sepolia
        version: {{vault_version}}
      - name: royco-vault-base
        version: {{vault_version}}
    type: subgraph_entity
  vault_raw_offer_reference:
    name: raw_offer
    subgraphs:
      - name: royco-vault-sepolia
        version: {{vault_version}}
      - name: royco-vault-mainnet
        version: {{vault_version}}
      - name: royco-vault-arbitrum-sepolia
        version: {{vault_version}}
      - name: royco-vault-arbitrum-one
        version: {{vault_version}}
      - name: royco-vault-base-sepolia
        version: {{vault_version}}
      - name: royco-vault-base
        version: {{vault_version}}
    type: subgraph_entity
  vault_raw_activity_reference:
    name: raw_activity
    subgraphs:
      - name: royco-vault-sepolia
        version: {{vault_version}}
      - name: royco-vault-mainnet
        version: {{vault_version}}
      - name: royco-vault-arbitrum-sepolia
        version: {{vault_version}}
      - name: royco-vault-arbitrum-one
        version: {{vault_version}}
      - name: royco-vault-base-sepolia
        version: {{vault_version}}
      - name: royco-vault-base
        version: {{vault_version}}
    type: subgraph_entity
  vault_raw_account_balance_reference:
    name: raw_account_balance
    subgraphs:
      - name: royco-vault-sepolia
        version: {{vault_version}}
      - name: royco-vault-mainnet
        version: {{vault_version}}
      - name: royco-vault-arbitrum-sepolia
        version: {{vault_version}}
      - name: royco-vault-arbitrum-one
        version: {{vault_version}}
      - name: royco-vault-base-sepolia
        version: {{vault_version}}
      - name: royco-vault-base
        version: {{vault_version}}
    type: subgraph_entity
transforms: {}
sinks:
  recipe_postgres_raw_market:
    type: postgres
    table: raw_markets
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_market"
    from: recipe_raw_market_reference
  recipe_postgres_raw_offer:
    type: postgres
    table: raw_offers
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_offer"
    from: recipe_raw_offer_reference
  recipe_postgres_raw_activity:
    type: postgres
    table: raw_activities
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_activity"
    from: recipe_raw_activity_reference
  recipe_postgres_raw_account_balance:
    type: postgres
    table: raw_account_balances_recipe
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_account_balance"
    from: recipe_raw_account_balance_reference
  recipe_postgres_raw_position:
    type: postgres
    table: raw_positions_recipe
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_position"
    from: recipe_raw_position_reference
  vault_postgres_raw_market:
    type: postgres
    table: raw_markets
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_market"
    from: vault_raw_market_reference
  vault_postgres_raw_offer:
    type: postgres
    table: raw_offers
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_offer"
    from: vault_raw_offer_reference
  vault_postgres_raw_activity:
    type: postgres
    table: raw_activities
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_activity"
    from: vault_raw_activity_reference
  vault_postgres_raw_account_balance:
    type: postgres
    table: raw_account_balances_vault
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_account_balance"
    from: vault_raw_account_balance_reference
