# prettier-ignore
apiVersion: 3
name: royco-goldsky-pipeline
status: ACTIVE
sources:
  recipe_raw_market_reference:
    name: raw_market
    subgraphs:
      - name: royco-recipe-sepolia
        version: {{recipe_version}}
      - name: royco-recipe-mainnet
        version: {{recipe_version}}
      - name: royco-recipe-arbitrum-one
        version: {{recipe_version}}
      - name: royco-recipe-base
        version: {{recipe_version}}
      - name: royco-recipe-plume
        version: {{recipe_version}}
      - name: royco-recipe-corn-maizenet
        version: {{recipe_version}}
      - name: royco-recipe-sonic
        version: {{recipe_version}}
    type: subgraph_entity
  recipe_raw_offer_reference:
    name: raw_offer
    subgraphs:
      - name: royco-recipe-sepolia
        version: {{recipe_version}}
      - name: royco-recipe-mainnet
        version: {{recipe_version}}
      - name: royco-recipe-arbitrum-one
        version: {{recipe_version}}
      - name: royco-recipe-base
        version: {{recipe_version}}
      - name: royco-recipe-plume
        version: {{recipe_version}}
      - name: royco-recipe-corn-maizenet
        version: {{recipe_version}}
      - name: royco-recipe-sonic
        version: {{recipe_version}}
    type: subgraph_entity
  recipe_raw_activity_reference:
    name: raw_activity
    subgraphs:
      - name: royco-recipe-sepolia
        version: {{recipe_version}}
      - name: royco-recipe-mainnet
        version: {{recipe_version}}
      - name: royco-recipe-arbitrum-one
        version: {{recipe_version}}
      - name: royco-recipe-base
        version: {{recipe_version}}
      - name: royco-recipe-plume
        version: {{recipe_version}}
      - name: royco-recipe-corn-maizenet
        version: {{recipe_version}}
      - name: royco-recipe-sonic
        version: {{recipe_version}}
    type: subgraph_entity
  recipe_raw_account_balance_reference:
    name: raw_account_balance
    subgraphs:
      - name: royco-recipe-sepolia
        version: {{recipe_version}}
      - name: royco-recipe-mainnet
        version: {{recipe_version}}
      - name: royco-recipe-arbitrum-one
        version: {{recipe_version}}
      - name: royco-recipe-base
        version: {{recipe_version}}
      - name: royco-recipe-plume
        version: {{recipe_version}}
      - name: royco-recipe-corn-maizenet
        version: {{recipe_version}}
      - name: royco-recipe-sonic
        version: {{recipe_version}}
    type: subgraph_entity 
  recipe_raw_position_reference:
    name: raw_position
    subgraphs:
      - name: royco-recipe-sepolia
        version: {{recipe_version}}
      - name: royco-recipe-mainnet
        version: {{recipe_version}}
      - name: royco-recipe-arbitrum-one
        version: {{recipe_version}}
      - name: royco-recipe-base
        version: {{recipe_version}}
      - name: royco-recipe-plume
        version: {{recipe_version}}
      - name: royco-recipe-corn-maizenet
        version: {{recipe_version}}
      - name: royco-recipe-sonic
        version: {{recipe_version}}
    type: subgraph_entity
  vault_raw_market_reference:
    name: raw_market
    subgraphs:
      - name: royco-vault-sepolia
        version: {{vault_version}}
      - name: royco-vault-mainnet
        version: {{vault_version}}
      - name: royco-vault-arbitrum-one
        version: {{vault_version}}
      - name: royco-vault-base
        version: {{vault_version}}
      - name: royco-vault-plume
        version: {{vault_version}}
      - name: royco-vault-corn-maizenet
        version: {{vault_version}}
      - name: royco-vault-sonic
        version: {{vault_version}}
    type: subgraph_entity
  vault_raw_offer_reference:
    name: raw_offer
    subgraphs:
      - name: royco-vault-sepolia
        version: {{vault_version}}
      - name: royco-vault-mainnet
        version: {{vault_version}}
      - name: royco-vault-arbitrum-one
        version: {{vault_version}}
      - name: royco-vault-base
        version: {{vault_version}}
      - name: royco-vault-plume
        version: {{vault_version}}
      - name: royco-vault-corn-maizenet
        version: {{vault_version}}
      - name: royco-vault-sonic
        version: {{vault_version}}
    type: subgraph_entity
  vault_raw_activity_reference:
    name: raw_activity
    subgraphs:
      - name: royco-vault-sepolia
        version: {{vault_version}}
      - name: royco-vault-mainnet
        version: {{vault_version}}
      - name: royco-vault-arbitrum-one
        version: {{vault_version}}
      - name: royco-vault-base
        version: {{vault_version}}
      - name: royco-vault-plume
        version: {{vault_version}}
      - name: royco-vault-corn-maizenet
        version: {{vault_version}}
      - name: royco-vault-sonic
        version: {{vault_version}}
    type: subgraph_entity
  vault_raw_account_balance_reference:
    name: raw_account_balance
    subgraphs:
      - name: royco-vault-sepolia
        version: {{vault_version}}
      - name: royco-vault-mainnet
        version: {{vault_version}}
      - name: royco-vault-arbitrum-one
        version: {{vault_version}}
      - name: royco-vault-base
        version: {{vault_version}}
      - name: royco-vault-plume
        version: {{vault_version}}
      - name: royco-vault-corn-maizenet
        version: {{vault_version}}
      - name: royco-vault-sonic
        version: {{vault_version}}
    type: subgraph_entity
  points_raw_points_reference:
    name: raw_point
    subgraphs:
      - name: royco-points-sepolia
        version: {{points_version}}
      - name: royco-points-mainnet
        version: {{points_version}}
      - name: royco-points-arbitrum-one
        version: {{points_version}}
      - name: royco-points-base
        version: {{points_version}}
      - name: royco-points-plume
        version: {{points_version}}
      - name: royco-points-corn-maizenet
        version: {{points_version}}
      - name: royco-points-sonic
        version: {{points_version}}
    type: subgraph_entity
  points_raw_point_balances_reference:
    name: raw_point_balance
    subgraphs:
      - name: royco-points-sepolia
        version: {{points_version}}
      - name: royco-points-mainnet
        version: {{points_version}}
      - name: royco-points-arbitrum-one
        version: {{points_version}}
      - name: royco-points-base
        version: {{points_version}}
      - name: royco-points-plume
        version: {{points_version}}
      - name: royco-points-corn-maizenet
        version: {{points_version}}
      - name: royco-points-sonic
        version: {{points_version}}
    type: subgraph_entity
  points_raw_awards_reference:
    name: raw_award
    subgraphs:
      - name: royco-points-sepolia
        version: {{points_version}}
      - name: royco-points-mainnet
        version: {{points_version}}
      - name: royco-points-arbitrum-one
        version: {{points_version}}
      - name: royco-points-base
        version: {{points_version}}
      - name: royco-points-plume
        version: {{points_version}}
      - name: royco-points-corn-maizenet
        version: {{points_version}}
      - name: royco-points-sonic
        version: {{points_version}}
    type: subgraph_entity
  points_raw_authorized_point_issuers_reference:
    name: raw_authorized_point_issuer
    subgraphs:
      - name: royco-points-sepolia
        version: {{points_version}}
      - name: royco-points-mainnet
        version: {{points_version}}
      - name: royco-points-arbitrum-one
        version: {{points_version}}
      - name: royco-points-base
        version: {{points_version}}
      - name: royco-points-plume
        version: {{points_version}}
      - name: royco-points-corn-maizenet
        version: {{points_version}}
      - name: royco-points-sonic
        version: {{points_version}}
    type: subgraph_entity
transforms: {}
sinks:
  recipe_postgres_raw_market:
    type: postgres
    table: raw_markets
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_market"
    from: recipe_raw_market_reference
  recipe_postgres_raw_offer:
    type: postgres
    table: raw_offers
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_offer"
    from: recipe_raw_offer_reference
  recipe_postgres_raw_activity:
    type: postgres
    table: raw_activities
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_activity"
    from: recipe_raw_activity_reference
  recipe_postgres_raw_account_balance:
    type: postgres
    table: raw_account_balances_recipe
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_account_balance"
    from: recipe_raw_account_balance_reference
  recipe_postgres_raw_position:
    type: postgres
    table: raw_positions_recipe
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_position"
    from: recipe_raw_position_reference
  vault_postgres_raw_market:
    type: postgres
    table: raw_markets
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_market"
    from: vault_raw_market_reference
  vault_postgres_raw_offer:
    type: postgres
    table: raw_offers
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_offer"
    from: vault_raw_offer_reference
  vault_postgres_raw_activity:
    type: postgres
    table: raw_activities
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_activity"
    from: vault_raw_activity_reference
  vault_postgres_raw_account_balance:
    type: postgres
    table: raw_account_balances_vault
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_account_balance"
    from: vault_raw_account_balance_reference
  points_postgres_raw_points:
    type: postgres
    table: raw_points
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_points"
    from: points_raw_points_reference
  points_postgres_raw_point_balances:
    type: postgres
    table: raw_point_balances
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_point_balances"
    from: points_raw_point_balances_reference
  points_postgres_raw_awards:
    type: postgres
    table: raw_awards
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_awards"
    from: points_raw_awards_reference
  points_postgres_raw_authorized_point_issuers:
    type: postgres
    table: raw_authorized_point_issuers
    schema: public
    secret_name: SUPABASE_ROYCO_FRONTEND
    description: "Postgres sink for: raw_authorized_point_issuers"
    from: points_raw_authorized_point_issuers_reference
